AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-ts-functions-layers

  Sample SAM Template for using functions and layers with Typescript

Globals:
  Function:
    Timeout: 3

Resources:
  LayerCommons:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/commons/
      CompatibleRuntimes:
        - nodejs16.x
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello-world/
      Handler: app.lambdaHandler
      Layers:
        - !Ref LayerCommons # the commons layer
      Runtime: nodejs16.x
      Architectures:
        - arm64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata: # esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        External:
          - commons # the layer module must be declared as external
        Minify: true
        Target: "es2020"
        EntryPoints:
          - app.ts

Outputs:
  HelloWorldApi:
    Description:
      "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
